language: r
r: bioc-devel
cache: packages

bioc_packages:
  - BiocCheck
  - BiocStyle
  
before_install:
  - Rscript -e "if (!require('covr')) install.packages('covr')"
  - Rscript -e 'update.packages(.libPaths()[1], ask = FALSE)'

script:
  - echo "R CMD BiocCheck ..."
  - R CMD BiocCheck 
  
